### ISSUE TITLE
Assets can not be found 404.

### ISSUE THREAD

**Issue by dirkpreus** [googlecodelabs/google-maps-simple-store-locator#15]
Running the below command creates the img directory but does not download the assets. The assets in the temp.zip are returned with a 404.

~/store-locator$ mkdir -p img; wget https://storage.googleapis.com/gmaps-store-locator/assets.zip -O temp.zip; unzip temp.zip -d img; rm temp.zip
--2020-06-25 09:17:44--  https://storage.googleapis.com/gmaps-store-locator/assets.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.214.128, 2607:f8b0:4001:c03::80
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.214.128|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-25 09:17:44 ERROR 404: Not Found.
Archive:  temp.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of temp.zip or
        temp.zip.zip, and cannot find temp.zip.ZIP, period.

**Comment by wangela** [comment]
Ah yes, that storage bucket is gone. I'll revise the codelab command to point to github. In the meantime, you can pull the image assets from https://github.com/googlecodelabs/google-maps-simple-store-locator/tree/master/src/img

**Comment by AtomicSpirit** [comment]
Stuck on this step.

**Comment by amin-nejad** [comment]
This should do it if you run from the `store-locator` directory:

```
wget https://github.com/googlecodelabs/google-maps-simple-store-locator/archive/master.zip
unzip master.zip
rm master.zip
mv google-maps-simple-store-locator-master/src/img/ .
rm -rf google-maps-simple-store-locator-master
```

**Comment by wangela** [comment]
Updated the [codelab instructions](https://developers.google.com/codelabs/maps-platform/google-maps-simple-store-locator#4) for this step. Copying the commands here for easy reference for those who don't want to download the whole repo:

```
mkdir -p img; cd img
wget https://github.com/googlecodelabs/google-maps-simple-store-locator/raw/master/src/img/icon_cafe.png
wget https://github.com/googlecodelabs/google-maps-simple-store-locator/raw/master/src/img/icon_patisserie.png
wget https://github.com/googlecodelabs/google-maps-simple-store-locator/raw/master/src/img/logo_cafe.png
wget https://github.com/googlecodelabs/google-maps-simple-store-locator/raw/master/src/img/logo_patisserie.png
```
