### ISSUE TITLE
Step 4: Hosting with Google Cloud Storage

### ISSUE THREAD

**Issue by unicorn74** [googlecodelabs/google-maps-simple-store-locator#2]
The third line of the input in step 4 of the "Hosting with Google Cloud Storage" codelab
`$ gsutil -h "Cache-Control:no-cache" cp * gs://gmaps-store-locators`
should be as follows: 
`$ gsutil -h "Cache-Control:no-cache" cp * gs://yourname-store-locator`
Please update the text of the codelab accordingly.

**Comment by stephenmcd** [comment]
Thanks, that's fixed now.
