### ISSUE TITLE
Replacing current locations with my own in stores.json nothing shows.

### ISSUE THREAD

**Issue by sammymwangangi** [googlecodelabs/google-maps-simple-store-locator#21]
The locations used in the original stores.json file load perfectly and everything else runs well. However, when I replace with my own locations, nothing loads on map, and if they do, they load on previous restricted country not mine and directions aren't calculated at all. I have already set _**componentRestrictions**_ option to my own country code and centered the map with my location coordinates.
Kindly, tell me what I am doing wrong.

**Comment by wangela** [comment]
@sammymwangangi would you mind sharing your stores.json file so we can compare the structure of your data?

**Comment by agasad** [comment]
I have same issue :/

**Comment by pgward1** [comment]
Facing same problem.  Did anyone get this resolved.

**Comment by wangela** [comment]
It's hard to troubleshoot without seeing any of your .json files, but my guess is you might need to specify which property in your json file to use as the unique "ID" of each store (feature in the GeoJson).

Notice in [app.js L120](https://github.com/googlecodelabs/google-maps-simple-store-locator/blob/master/src/app.js#L120) the second parameter passed to `loadGeoJson` is `idPropertyName` with a value of `storeid` which corresponds to the `properties > storeid` property in the sample [stores.json](https://raw.githubusercontent.com/googlecodelabs/google-maps-simple-store-locator/master/src/stores.json) file. If your .json file uses a different property name as the unique identifier for each feature in your .json file, you need to adjust the `idPropertyName` parameter value to match that.

Documentation: [Data.GeoJsonOptions interface](https://developers.google.com/maps/documentation/javascript/reference/data#Data.GeoJsonOptions)

Please reopen with a sample of your .json file if you are still having issues after taking the above into account.
