### ISSUE TITLE
a sidebar should appear listing the store locations - Not working

### ISSUE THREAD

**Issue by PLAUK1** [googlecodelabs/google-maps-simple-store-locator#24]
Hi Guys,
Step 4 or Point "7. List the closest stores"
"Finally, enter a UK address into the Autocomplete search bar and click on one of the suggestions.
The map should center on that address and a sidebar should appear listing the store locations in order of distance from the selected address. One example is pictured as follows:"
Is not working

**Comment by wangela** [comment]
You might want to check if Distance Matrix API is enabled for your project (follow the [recently revised setup instructions again](https://developers.google.com/codelabs/maps-platform/google-maps-simple-store-locator#1) for your project). Issue #17 reported that one product was missing from the setup step, and this step won't work if that API isn't enabled to generate the ordered list of stores. Please reopen if you are still experiencing this issue after fixing the API enablement.
