### ISSUE TITLE
Unable to separate JS & HTML

### ISSUE THREAD

**Issue by AnandWalvekar** [googlecodelabs/google-maps-simple-store-locator#3]
Hi @stephenmcd 
I tried with the code given but it keeps giving error as in attachment. However if I move the js code to the same html file it works fine.

<img width="1154" alt="screen shot 2017-10-31 at 4 46 00 pm" src="https://user-images.githubusercontent.com/349903/32221323-1b860fb0-be5b-11e7-8af7-02d65f3ecb3a.png">

**Comment by wangela** [comment]
If you made sure to include [index.html Line 27](https://github.com/googlecodelabs/google-maps-simple-store-locator/blob/master/src/index.html#L27) referencing app.js in a script tag, then initMap should have been found in app.js (see [app.js line 124](https://github.com/googlecodelabs/google-maps-simple-store-locator/blob/master/src/app.js#L124)).
