### ISSUE TITLE
A link to an example

### ISSUE THREAD

**Issue by MPParsley** [googlecodelabs/google-maps-simple-store-locator#6]
A link to an example app that demonstrates the end result would be useful.

**Comment by alboteanud** [comment]
final result should look like mine here: http://storage.googleapis.com/alboteanu-store-locatoral/index.html

**Comment by wangela** [comment]
The [codelab](https://codelabs.developers.google.com/codelabs/google-maps-simple-store-locator/) now has more screenshots so you can see what the result should look like.
