### ISSUE TITLE
Store list does not show up

### ISSUE THREAD

**Issue by youdar** [googlecodelabs/google-maps-simple-store-locator#9]
Hi,
I followed the codelab https://codelabs.developers.google.com/codelabs/google-maps-simple-store-locator

In step 7, the store list does not show up, even if I just copy the code directly from the git repo and only change the "YOUR_API_KEY "

Thanks

**Comment by wangela** [comment]
Thanks for doing the codelab, @youdar. 
Would you take a look at your JavaScript console and share any error messages you see?

**Comment by youdar** [comment]
Is this what you mean?

[image: Annotation 2019-12-08 215154.jpg]

**Comment by youdar** [comment]
This is the Error:
`content.min.js:2 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M80, around February 2020. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.`

**Comment by youdar** [comment]
Content.min.js:2
`function(a){var b=function(b){this.K=b.instanceId;this.J=a;b=document.createElement("div");var c=document.createElement("a");c.target="_blank";this.F=b.cloneNode(!1);this.B=document.createElement("audio");this.B.R=!0;this.b=b.cloneNode(!1);this.b.id="gdx-bubble-host";this.D=this.b.createShadowRoot?this.b.createShadowRoot():this.b.webkitCreateShadowRoot();var f=document.createElement("style");f.innerHTML=this.J;this.D.appendChild(f);this.a=b.cloneNode(!1);this.a.id="gdx-bubble-main";this.D.appendChild(this.a);`

**Comment by wangela** [comment]
I have also just cloned the repo, replaced the YOUR_API_KEY in index.html and app.js, and I'm unable to reproduce your error (I'm hosting on a python server via gcloud as instructed in the codelab). It might be one of your browser extensions that is causing this error. See [this SO answer](https://stackoverflow.com/a/53953310/8805781) that explains how to figure out which file is actually triggering that error.

**Comment by youdar** [comment]
Starting from the beginning:  
- Laptop: MacBook with OS High Sierra 10.13.6    
- Browser:  Version 78.0.3904.108 (Official Build) (64-bit)   

- [Simple Store Locator with Google Maps](https://codelabs.developers.google.com/codelabs/google-maps-simple-store-locator/#0)  
- following instruction step by step  
- going to https://console.cloud.google.com/cloud-resource-manager?organizationId=0 deleted the previous project and created a new project, copying from the git
- created a new API key and enable it and replace it in app.js and index.html  
- tried on Chrome and FireFox and in both I do not get the side list

**Comment by youdar** [comment]
Redo everything, tried on both chrome and firefox and I get the same issue,
not list of stores on the side of the webpage

[image: Screen Shot 2020-01-05 at 10.26.43 PM.png]

**Comment by youdar** [comment]
message in firefox was a little different

[image: Screen Shot 2020-01-05 at 10.29.39 PM.png]

**Comment by dirkpreus** [comment]
I had this same issue and enabling the Distance Matrix API in the market place fixed the problem and the list is now showing up.
